version: "3.8"
services:
  ddev-lab-postres:
    image: postgres:15.5-alpine
    container_name: ddev-lab-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

networks:
  default:
    name: ddev-lab
    external: true